### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by AlgerFan** [wangjingxiao/vue-music#2]
1. 字体不好看，建议更换字体
2. 标题较小

**Comment by wangjingxiao** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlgerFan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 晚上7:46
收件人:&nbsp;"wangjingxiao/vue-music"<vue-music@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wangjingxiao/vue-music] 样式问题 (#2)



 
字体不好看，建议更换字体
 
标题较小
